# Bibliotecas Externas

En este JNB se revisará el tema de Bibliotecas Externas.

In [2]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [3]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
print(dir(math))

In [4]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [5]:
math.pi

3.141592653589793

In [6]:
math.log(32, 2)

5.0

In [7]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.

    If the base is not specified, returns the natural logarithm (base e) of x.



In [8]:
math.e

2.718281828459045

In [9]:
import math as mt
mt.pi

3.141592653589793

In [10]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [13]:
from math import log, pi
from numpy import asarray
print(pi, log(32, 2))

3.141592653589793 5.0


In [14]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [15]:
# Roll 10 dice
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([1, 4, 4, 1, 4, 2, 1, 2, 4, 3])

In [16]:
[3, 4, 1, 2, 2, 1] + 10

TypeError: can only concatenate list (not "int") to list

In [17]:
rolls + 10

array([11, 14, 14, 11, 14, 12, 11, 12, 14, 13])

In [18]:
# At which indices are the dice less than or equal to 3?
rolls <= 3

array([ True, False, False,  True, False,  True,  True,  True, False,
        True])

In [19]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [20]:
# Get the last element of the second row of our numpy array
x[1,-1]

np.int64(6)